/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ZTERmodel;

import java.sql.DriverManager;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;



/**
 *
 * @author haseena
 */
public class Customer extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    private DefaultTableModel model;
    private Timer timer;
    private SimpleDateFormat dateFormat;

    public Customer() {
        initComponents();
        
         model = new DefaultTableModel();
    sold_tickets.setModel(model);
    model.addColumn("movieid");
    model.addColumn("title");
    model.addColumn("showing Date");
    model.addColumn("rate sP");
    model.addColumn("rate nP");
    
    
            fetchDataFromDatabase();    
            
    timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                updateTextFieldWithTime();
            }
        });
        timer.start();
        
    
        dateFormat = new SimpleDateFormat("HH:mm:ss");
        
   
        updateTextFieldWithTime();
    }

    private void updateTextFieldWithTime() {
        Date currentTime = new Date();
        String formattedTime = dateFormat.format(currentTime);
        timing.setText(formattedTime);
    }

    private void fetchDataFromDatabase() {
    try {

        java.sql.Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/zter", "root", "0212hk");
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery("SELECT movieId, title, showing_date, rate_sp, rate_np FROM movies");
        
        // Clear existing rows from the table
        model.setRowCount(0);
        
        // Fetch data from the result set and add it to the table
        while (rs.next()) {
            int movieId = rs.getInt("movieId");  
            String title = rs.getString("title");
            String showingDate = rs.getString("showing_date");
            int rateSp = rs.getInt("rate_sp");
            int rateNp = rs.getInt("rate_np");
            
            model.addRow(new Object[]{movieId, title, showingDate, rateSp, rateNp});
        }
        
        rs.close();
        stmt.close();
        conn.close();
    } catch (SQLException e) {
        System.out.println(e.getMessage());
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sold_tickets = new javax.swing.JTable();
        lblshowingdate = new javax.swing.JLabel();
        lbltitle = new javax.swing.JLabel();
        lblratenp = new javax.swing.JLabel();
        txt_ratenp = new javax.swing.JTextField();
        txt_title = new javax.swing.JTextField();
        txt_ratesp = new javax.swing.JTextField();
        timing = new javax.swing.JTextField();
        cancelbtn = new javax.swing.JButton();
        txt_showingdate = new javax.swing.JTextField();
        lbltiming = new javax.swing.JLabel();
        lblratesp = new javax.swing.JLabel();
        entryllbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sold_tickets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "movieId", "title", "showing date", "rate sp", "rate np", "time checked"
            }
        ));
        sold_tickets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sold_ticketsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(sold_tickets);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 190, 550, 570));

        lblshowingdate.setText("showing_date");
        jPanel1.add(lblshowingdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, -1, -1));

        lbltitle.setText("title");
        jPanel1.add(lbltitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        lblratenp.setText("rate_np");
        jPanel1.add(lblratenp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, -1, -1));

        txt_ratenp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ratenpActionPerformed(evt);
            }
        });
        jPanel1.add(txt_ratenp, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 150, -1));

        txt_title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_titleActionPerformed(evt);
            }
        });
        jPanel1.add(txt_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 150, -1));

        txt_ratesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ratespActionPerformed(evt);
            }
        });
        jPanel1.add(txt_ratesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 150, -1));
        jPanel1.add(timing, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, 150, 30));

        cancelbtn.setText("cancled");
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });
        jPanel1.add(cancelbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, -1, -1));

        txt_showingdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_showingdateActionPerformed(evt);
            }
        });
        jPanel1.add(txt_showingdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 150, -1));

        lbltiming.setText("Time ");
        jPanel1.add(lbltiming, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, -1, -1));

        lblratesp.setText("rate_sp");
        jPanel1.add(lblratesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, -1));

        entryllbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ZterView/table.png"))); // NOI18N
        jPanel1.add(entryllbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 360, 440));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ZterView/Add movie.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 1480, 640));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ZterView/BGBG.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 800));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ratenpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ratenpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ratenpActionPerformed

    private void txt_titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_titleActionPerformed

    private void txt_showingdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_showingdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_showingdateActionPerformed

    private void txt_ratespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ratespActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ratespActionPerformed

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
         int selectedRowIndex = sold_tickets.getSelectedRow();
    if (selectedRowIndex != -1) { // Check if a row is selected
        int movieId = (int) sold_tickets.getValueAt(selectedRowIndex, 0);

        // Delete the row from the database
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/zter", "root", "0212hk");
            Statement stmt = conn.createStatement();
            String query = "DELETE FROM movies WHERE movieId = " + movieId;
            int rowsAffected = stmt.executeUpdate(query);
            stmt.close();
            conn.close();

            if (rowsAffected > 0) {
                // Delete the row from the table model
                model.removeRow(selectedRowIndex);
                JOptionPane.showMessageDialog(this, "Data canceled successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to cancel data.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    }//GEN-LAST:event_cancelbtnActionPerformed

    private void sold_ticketsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sold_ticketsMouseClicked

        int selectedRowIndex = sold_tickets.getSelectedRow();
    txt_title.setText(sold_tickets.getValueAt(selectedRowIndex, 1).toString());
    txt_showingdate.setText(sold_tickets.getValueAt(selectedRowIndex, 2).toString());
    txt_ratesp.setText(sold_tickets.getValueAt(selectedRowIndex, 3).toString());
    txt_ratenp.setText(sold_tickets.getValueAt(selectedRowIndex, 4).toString());
    }//GEN-LAST:event_sold_ticketsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelbtn;
    private javax.swing.JLabel entryllbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblratenp;
    private javax.swing.JLabel lblratesp;
    private javax.swing.JLabel lblshowingdate;
    private javax.swing.JLabel lbltiming;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JTable sold_tickets;
    private javax.swing.JTextField timing;
    private javax.swing.JTextField txt_ratenp;
    private javax.swing.JTextField txt_ratesp;
    private javax.swing.JTextField txt_showingdate;
    private javax.swing.JTextField txt_title;
    // End of variables declaration//GEN-END:variables
}
