/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ZTER;

/**
 *
 * @author haseena
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Profile_btn = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        Addmovie_btn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        editstreaming_btn = new javax.swing.JButton();
        customer_btn = new javax.swing.JButton();
        Availablemovie_btn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zter images/movie ticketing/Z-TER.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 90, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zter images/movie ticketing/movie-projector 2.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 80));

        Profile_btn.setBackground(new java.awt.Color(0, 0, 0));
        Profile_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zter images/movie ticketing/icons8-user-50.png"))); // NOI18N
        Profile_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Profile_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Profile_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, 40, 40));

        jButton6.setIcon(new javax.swing.ImageIcon("/home/haseena/Downloads/movie ticketing/tarMOviename.png")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 200, 230));

        Addmovie_btn.setText("Add Movie");
        jPanel1.add(Addmovie_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        jButton2.setText("Available Movie");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, -1, -1));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zter images/the-handmaiden-movie-poster 1.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 180, 270));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zter images/896414f828ce06accbffc54cad11ab34 1.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 160, 210));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zter images/doctor-strange-in-the-universe-of-madness-i127944 2.png"))); // NOI18N
        jButton9.setText("jButton9");
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 170, 250));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zter images/Exo.png"))); // NOI18N
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 210, 340));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zter images/kill-bill-vol-1-md-web 1.png"))); // NOI18N
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 170, 160, 240));

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zter images/knives Out.png"))); // NOI18N
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 160, 240));

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ZTER/section 1.png"))); // NOI18N
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 200, 250));

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zter images/Hannibal 1.png"))); // NOI18N
        jPanel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 440, 180, 270));

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zter images/slenderman 1.png"))); // NOI18N
        jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 420, 190, 290));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zter images/movie ticketing/Dashboardlessvisible.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 1100, 620));

        editstreaming_btn.setText("Edit Streaming");
        jPanel1.add(editstreaming_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, -1, -1));

        customer_btn.setText("Customer");
        jPanel1.add(customer_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 70, -1, -1));

        Availablemovie_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zter images/movie ticketing/playing.png"))); // NOI18N
        jPanel1.add(Availablemovie_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Profile_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Profile_btnActionPerformed
        Profile p = new Profile();
        p.setVisible(true);
    }//GEN-LAST:event_Profile_btnActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addmovie_btn;
    private javax.swing.JLabel Availablemovie_btn;
    private javax.swing.JButton Profile_btn;
    private javax.swing.JButton customer_btn;
    private javax.swing.JButton editstreaming_btn;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
