/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ZTER;

/**
 *
 * @author haseena
 */
//import javax.swing.JLabel;
public class Dashboard extends javax.swing.JFrame {

    private Object contentPane;

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frstpanel = new javax.swing.JPanel();
        lbl_Zter = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();
        Profile_btn = new javax.swing.JButton();
        fstMovie_btn = new javax.swing.JButton();
        Addmovie_btn = new javax.swing.JButton();
        AvailableMovie_btn = new javax.swing.JButton();
        SecMovie_btn = new javax.swing.JButton();
        TrdMovie_btn = new javax.swing.JButton();
        EghMovie_btn = new javax.swing.JButton();
        FourthMovie_btn = new javax.swing.JButton();
        fifthMovie_btn = new javax.swing.JButton();
        sixthMovie_btn = new javax.swing.JButton();
        SeventhMovie_btn = new javax.swing.JButton();
        NinethMovies_btn = new javax.swing.JButton();
        TenthMovie_btn = new javax.swing.JButton();
        collectMovie_lbl = new javax.swing.JLabel();
        editstreaming_btn = new javax.swing.JButton();
        customer_btn = new javax.swing.JButton();
        Availablemovie_btn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(214783647, 2147483647));
        setName("Main frame"); // NOI18N

        frstpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Zter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zter images/movie ticketing/Z-TER.png"))); // NOI18N
        frstpanel.add(lbl_Zter, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 90, 60));

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zter images/movie ticketing/movie-projector 2.png"))); // NOI18N
        frstpanel.add(lbl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 80));

        Profile_btn.setBackground(new java.awt.Color(0, 0, 0));
        Profile_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zter images/movie ticketing/icons8-user-50.png"))); // NOI18N
        Profile_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Profile_btnActionPerformed(evt);
            }
        });
        frstpanel.add(Profile_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, 40, 40));

        fstMovie_btn.setIcon(new javax.swing.ImageIcon("/home/haseena/Downloads/movie ticketing/tarMOviename.png")); // NOI18N
        fstMovie_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fstMovie_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fstMovie_btnMouseEntered(evt);
            }
        });
        fstMovie_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fstMovie_btnActionPerformed(evt);
            }
        });
        frstpanel.add(fstMovie_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 200, 230));

        Addmovie_btn.setText("Add Movie");
        Addmovie_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Addmovie_btnActionPerformed(evt);
            }
        });
        frstpanel.add(Addmovie_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        AvailableMovie_btn.setText("Available Movie");
        AvailableMovie_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvailableMovie_btnActionPerformed(evt);
            }
        });
        frstpanel.add(AvailableMovie_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, -1, -1));

        SecMovie_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zter images/the-handmaiden-movie-poster 1.png"))); // NOI18N
        SecMovie_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecMovie_btnActionPerformed(evt);
            }
        });
        frstpanel.add(SecMovie_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 180, 270));

        TrdMovie_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zter images/896414f828ce06accbffc54cad11ab34 1.png"))); // NOI18N
        TrdMovie_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrdMovie_btnActionPerformed(evt);
            }
        });
        frstpanel.add(TrdMovie_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 160, 210));

        EghMovie_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zter images/Exo.png"))); // NOI18N
        frstpanel.add(EghMovie_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 210, 340));

        FourthMovie_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zter images/doctor-strange-in-the-universe-of-madness-i127944 2.png"))); // NOI18N
        FourthMovie_btn.setText("jButton9");
        frstpanel.add(FourthMovie_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 170, 250));

        fifthMovie_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zter images/kill-bill-vol-1-md-web 1.png"))); // NOI18N
        frstpanel.add(fifthMovie_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 170, 160, 240));

        sixthMovie_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zter images/knives Out.png"))); // NOI18N
        frstpanel.add(sixthMovie_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 160, 240));

        SeventhMovie_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zter images/section 1.png"))); // NOI18N
        frstpanel.add(SeventhMovie_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 200, 250));

        NinethMovies_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zter images/Hannibal 1.png"))); // NOI18N
        frstpanel.add(NinethMovies_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 440, 180, 270));

        TenthMovie_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zter images/slenderman 1.png"))); // NOI18N
        frstpanel.add(TenthMovie_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 420, 190, 290));

        collectMovie_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zter images/movie ticketing/Dashboardlessvisible.png"))); // NOI18N
        frstpanel.add(collectMovie_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 1100, 620));

        editstreaming_btn.setText("Edit Streaming");
        editstreaming_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editstreaming_btnActionPerformed(evt);
            }
        });
        frstpanel.add(editstreaming_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, -1, -1));

        customer_btn.setText("Customer");
        customer_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_btnActionPerformed(evt);
            }
        });
        frstpanel.add(customer_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 70, -1, -1));

        Availablemovie_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zter images/movie ticketing/playing.png"))); // NOI18N
        frstpanel.add(Availablemovie_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(frstpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(frstpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Profile_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Profile_btnActionPerformed
        Profile p = new Profile();
        p.setVisible(true);
        frstpanel.getParent().remove(frstpanel);
    }//GEN-LAST:event_Profile_btnActionPerformed

    private void fstMovie_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fstMovie_btnActionPerformed
       
    }//GEN-LAST:event_fstMovie_btnActionPerformed

    private void SecMovie_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecMovie_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SecMovie_btnActionPerformed

    private void TrdMovie_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrdMovie_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TrdMovie_btnActionPerformed

    private void Addmovie_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Addmovie_btnActionPerformed
        // TODO add your handling code here:
        AddMovies add = new AddMovies();
        add.setVisible(true);
    }//GEN-LAST:event_Addmovie_btnActionPerformed

    private void AvailableMovie_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvailableMovie_btnActionPerformed
        // TODO add your handling code here:
        AvailableMovies avbl = new AvailableMovies();
        avbl.setVisible(true);
    }//GEN-LAST:event_AvailableMovie_btnActionPerformed

    private void editstreaming_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editstreaming_btnActionPerformed
        // TODO add your handling code here:
        EditStreaming edit = new EditStreaming();
        edit.setVisible(true);
    }//GEN-LAST:event_editstreaming_btnActionPerformed

    private void customer_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_btnActionPerformed
        // TODO add your handling code here:
        Customer cust = new Customer();
        cust.setVisible(true);
    }//GEN-LAST:event_customer_btnActionPerformed

    private void fstMovie_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fstMovie_btnMouseEntered

    }//GEN-LAST:event_fstMovie_btnMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addmovie_btn;
    private javax.swing.JButton AvailableMovie_btn;
    private javax.swing.JLabel Availablemovie_btn;
    private javax.swing.JButton EghMovie_btn;
    private javax.swing.JButton FourthMovie_btn;
    private javax.swing.JButton NinethMovies_btn;
    private javax.swing.JButton Profile_btn;
    private javax.swing.JButton SecMovie_btn;
    private javax.swing.JButton SeventhMovie_btn;
    private javax.swing.JButton TenthMovie_btn;
    private javax.swing.JButton TrdMovie_btn;
    private javax.swing.JLabel collectMovie_lbl;
    private javax.swing.JButton customer_btn;
    private javax.swing.JButton editstreaming_btn;
    private javax.swing.JButton fifthMovie_btn;
    private javax.swing.JPanel frstpanel;
    private javax.swing.JButton fstMovie_btn;
    private javax.swing.JLabel lbl_Zter;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JButton sixthMovie_btn;
    // End of variables declaration//GEN-END:variables
}
