package model;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import model.login;
import model.DbConnection;
import java.sql.*;
import javax.swing.JOptionPane;
public class registration_page extends javax.swing.JFrame {

    Statement stmt;
    Connection conn;
    public registration_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        already_have_an_account_button = new javax.swing.JToggleButton();
        confirm_password_field = new javax.swing.JTextField();
        password_field = new javax.swing.JTextField();
        username_field = new javax.swing.JTextField();
        email_field = new javax.swing.JTextField();
        register_button = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        username_field1 = new javax.swing.JTextField();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        already_have_an_account_button.setBackground(new java.awt.Color(46, 74, 81));
        already_have_an_account_button.setForeground(new java.awt.Color(255, 255, 255));
        already_have_an_account_button.setText("ALREADY HAVE AN ACCOUNT?");
        already_have_an_account_button.setBorder(null);
        already_have_an_account_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                already_have_an_account_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(already_have_an_account_button);
        already_have_an_account_button.setBounds(390, 750, 210, 30);

        confirm_password_field.setBackground(new java.awt.Color(46, 74, 81));
        confirm_password_field.setForeground(new java.awt.Color(255, 255, 255));
        confirm_password_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        confirm_password_field.setText("CONFIRM PASSOWRD");
        confirm_password_field.setBorder(null);
        getContentPane().add(confirm_password_field);
        confirm_password_field.setBounds(190, 680, 580, 30);

        password_field.setBackground(new java.awt.Color(46, 74, 81));
        password_field.setForeground(new java.awt.Color(255, 255, 255));
        password_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password_field.setText("PASSWORD");
        password_field.setBorder(null);
        getContentPane().add(password_field);
        password_field.setBounds(190, 590, 580, 30);

        username_field.setBackground(new java.awt.Color(46, 74, 81));
        username_field.setForeground(new java.awt.Color(255, 255, 255));
        username_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username_field.setText("USERNAME");
        username_field.setBorder(null);
        username_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_fieldActionPerformed(evt);
            }
        });
        getContentPane().add(username_field);
        username_field.setBounds(190, 380, 580, 30);

        email_field.setBackground(new java.awt.Color(46, 74, 81));
        email_field.setForeground(new java.awt.Color(255, 255, 255));
        email_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email_field.setText("EMAIL");
        email_field.setBorder(null);
        email_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_fieldActionPerformed(evt);
            }
        });
        getContentPane().add(email_field);
        email_field.setBounds(190, 490, 580, 30);

        register_button.setBackground(new java.awt.Color(51, 51, 51));
        register_button.setForeground(new java.awt.Color(255, 255, 255));
        register_button.setText("REGISTER");
        register_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(register_button);
        register_button.setBounds(640, 730, 150, 60);

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\Z-TER\\images\\final.jpg")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, -20, 1529, 1060);

        username_field1.setBackground(new java.awt.Color(46, 74, 81));
        username_field1.setForeground(new java.awt.Color(255, 255, 255));
        username_field1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username_field1.setText("USERNAME");
        username_field1.setBorder(null);
        username_field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_field1ActionPerformed(evt);
            }
        });
        getContentPane().add(username_field1);
        username_field1.setBounds(170, 380, 580, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void username_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_fieldActionPerformed

    private void email_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_fieldActionPerformed

    private void register_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_buttonActionPerformed
        // TODO add your handling code here:
        try {
            conn = DbConnection.dbConnect();
            stmt = conn.createStatement();
            String sql = "SELECT * FROM admin WHERE email='" + email_field.getText() + "'";
            ResultSet rs = stmt.executeQuery(sql);

            boolean userExists = rs.next();
            if (userExists) {
                JOptionPane.showMessageDialog(rootPane, "User already registered");
            } else {
                if (confirm_password_field.getText().equals(password_field.getText())) {
                    String insertSql = "INSERT INTO admin (username, password, email) VALUES (?, ?, ?)";
                    PreparedStatement insertStmt = conn.prepareStatement(insertSql);
                    insertStmt.setString(1, username_field.getText());
                    insertStmt.setString(2, password_field.getText());
                    insertStmt.setString(3, email_field.getText());

                    insertStmt.executeUpdate();
                    JOptionPane.showMessageDialog(rootPane, "User registered successfully");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "The password does not match the confirm password");
                }
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_register_buttonActionPerformed

    private void username_field1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_field1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_field1ActionPerformed

    private void already_have_an_account_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_already_have_an_account_buttonActionPerformed
        login l1= new login();
        l1.show();
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_already_have_an_account_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registration_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registration_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registration_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registration_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registration_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton already_have_an_account_button;
    private javax.swing.JTextField confirm_password_field;
    private javax.swing.JTextField email_field;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField password_field;
    private javax.swing.JButton register_button;
    private javax.swing.JTextField username_field;
    private javax.swing.JTextField username_field1;
    // End of variables declaration//GEN-END:variables
}
