/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.edit_screening_controller;
import java.awt.Color;
import java.awt.Toolkit;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aashish
 */
public class edit_screening extends javax.swing.JFrame {

    /**
     * Creates new form edit_screening_controller
     */
    public edit_screening() {
        initComponents();
        setTitle("Edit Screening");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/movie-projector 2.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        edit_screening_controller edc1 = new edit_screening_controller();

        Set<String> stringSet = edc1.getMoviesData();
        String[] stringArray = stringSet.toArray(new String[stringSet.size()]);
        String[][] data = new String[stringArray.length][3];
        jTable1 = new javax.swing.JTable();
        title_label = new javax.swing.JLabel();
        btn_update = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        entryllbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        logout = new javax.swing.JPanel();
        logout_lbl = new javax.swing.JLabel();
        profile_panel1 = new javax.swing.JPanel();
        profile_lbl1 = new javax.swing.JLabel();
        dashboard_btn = new javax.swing.JPanel();
        lbl_dashboard = new javax.swing.JLabel();
        pnl_admovie3 = new javax.swing.JPanel();
        lbl_admovie3 = new javax.swing.JLabel();
        edit_screeningpnl = new javax.swing.JPanel();
        lbl_editscreen = new javax.swing.JLabel();
        pnl_avmovie = new javax.swing.JPanel();
        lbl_avmovie = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        menu_lbl = new javax.swing.JLabel();
        customer_pnl = new javax.swing.JPanel();
        lbl_customer1 = new javax.swing.JLabel();
        bg_pic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1547, 805));
        setResizable(false);
        getContentPane().setLayout(null);

        int row = 0;
        for (String rowData : stringArray) { // Corrected the loop variable type
            data[row] = rowData.split(","); // Assuming rowData is a comma-separated string
            row++;
        }
        String[] columnNames = {"Movie", "Genre", "Showing Status"};
        DefaultTableModel model = new DefaultTableModel(data, columnNames);
        jTable1.setModel(model);
        jTable1.setGridColor(new java.awt.Color(0, 102, 102));
        jTable1.setRowHeight(19);
        jTable1.setSelectionBackground(new java.awt.Color(0, 51, 51));
        jTable1.setShowGrid(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(710, 210, 680, 490);

        title_label.setBackground(new java.awt.Color(0, 0, 0));
        title_label.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        title_label.setForeground(new java.awt.Color(255, 255, 255));
        title_label.setText("Title");
        getContentPane().add(title_label);
        title_label.setBounds(330, 300, 280, 28);

        btn_update.setBackground(new java.awt.Color(0, 0, 0));
        btn_update.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 16)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setText("UPDATE");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        getContentPane().add(btn_update);
        btn_update.setBounds(470, 560, 120, 30);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(210, 560, 120, 30);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CURRENT :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 410, 110, 30);

        jComboBox2.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "showing ", "not showing " }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(410, 410, 180, 30);

        entryllbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ZterView/Rectangle 46.png"))); // NOI18N
        getContentPane().add(entryllbl);
        entryllbl.setBounds(150, 210, 490, 490);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 200, 240, 310);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zter images/movie ticketing/dbframe.png"))); // NOI18N
        jLabel5.setText("\\");
            getContentPane().add(jLabel5);
            jLabel5.setBounds(70, 150, 1384, 595);

            panel.setBackground(new java.awt.Color(0, 0, 0));
            panel.setForeground(new java.awt.Color(0, 102, 102));
            panel.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    panelMouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    panelMouseExited(evt);
                }
            });
            panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            logout.setBackground(new java.awt.Color(39, 88, 88));
            logout.setBorder(javax.swing.BorderFactory.createEtchedBorder());
            logout.setForeground(new java.awt.Color(255, 255, 255));
            logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            logout_lbl.setBackground(new java.awt.Color(59, 87, 94));
            logout_lbl.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 15)); // NOI18N
            logout_lbl.setForeground(new java.awt.Color(255, 255, 255));
            logout_lbl.setText("  LOG OUT");
            logout_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    logout_lblMouseClicked(evt);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    logout_lblMouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    logout_lblMouseExited(evt);
                }
            });
            logout.add(logout_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 20));

            panel.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 80, 20));

            profile_panel1.setBackground(new java.awt.Color(39, 88, 88));
            profile_panel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
            profile_panel1.setForeground(new java.awt.Color(255, 255, 255));
            profile_panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            profile_lbl1.setBackground(new java.awt.Color(46, 74, 81));
            profile_lbl1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 15)); // NOI18N
            profile_lbl1.setForeground(new java.awt.Color(255, 255, 255));
            profile_lbl1.setText("  PROFILE");
            profile_lbl1.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    profile_lbl1MouseClicked(evt);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    profile_lbl1MouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    profile_lbl1MouseExited(evt);
                }
            });
            profile_panel1.add(profile_lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, -1));

            panel.add(profile_panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 80, 20));

            getContentPane().add(panel);
            panel.setBounds(1340, 50, 80, 0);

            dashboard_btn.setBackground(new java.awt.Color(46, 74, 81));
            dashboard_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
            dashboard_btn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            lbl_dashboard.setFont(new java.awt.Font("Franklin Gothic Book", 1, 20)); // NOI18N
            lbl_dashboard.setForeground(new java.awt.Color(255, 255, 255));
            lbl_dashboard.setText("Dashboard");
            lbl_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    lbl_dashboardMouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    lbl_dashboardMouseExited(evt);
                }
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    lbl_dashboardMousePressed(evt);
                }
            });
            dashboard_btn.add(lbl_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -6, -1, 40));

            getContentPane().add(dashboard_btn);
            dashboard_btn.setBounds(280, 70, 120, 34);

            pnl_admovie3.setBackground(new java.awt.Color(46, 74, 81));
            pnl_admovie3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

            lbl_admovie3.setFont(new java.awt.Font("Franklin Gothic Book", 1, 20)); // NOI18N
            lbl_admovie3.setForeground(new java.awt.Color(255, 255, 255));
            lbl_admovie3.setText("Add Movies");
            lbl_admovie3.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    lbl_admovie3MouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    lbl_admovie3MouseExited(evt);
                }
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    lbl_admovie3MousePressed(evt);
                }
            });

            javax.swing.GroupLayout pnl_admovie3Layout = new javax.swing.GroupLayout(pnl_admovie3);
            pnl_admovie3.setLayout(pnl_admovie3Layout);
            pnl_admovie3Layout.setHorizontalGroup(
                pnl_admovie3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_admovie3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbl_admovie3)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            pnl_admovie3Layout.setVerticalGroup(
                pnl_admovie3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_admovie3Layout.createSequentialGroup()
                    .addGap(0, 2, Short.MAX_VALUE)
                    .addComponent(lbl_admovie3))
            );

            getContentPane().add(pnl_admovie3);
            pnl_admovie3.setBounds(510, 70, 130, 30);

            edit_screeningpnl.setBackground(new java.awt.Color(0, 0, 0));
            edit_screeningpnl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

            lbl_editscreen.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
            lbl_editscreen.setForeground(new java.awt.Color(255, 255, 255));
            lbl_editscreen.setText("EDIT SCREENING");
            lbl_editscreen.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    lbl_editscreenMouseClicked(evt);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    lbl_editscreenMouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    lbl_editscreenMouseExited(evt);
                }
            });

            javax.swing.GroupLayout edit_screeningpnlLayout = new javax.swing.GroupLayout(edit_screeningpnl);
            edit_screeningpnl.setLayout(edit_screeningpnlLayout);
            edit_screeningpnlLayout.setHorizontalGroup(
                edit_screeningpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 156, Short.MAX_VALUE)
                .addGroup(edit_screeningpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(edit_screeningpnlLayout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addComponent(lbl_editscreen)
                        .addGap(0, 7, Short.MAX_VALUE)))
            );
            edit_screeningpnlLayout.setVerticalGroup(
                edit_screeningpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 26, Short.MAX_VALUE)
                .addGroup(edit_screeningpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(edit_screeningpnlLayout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addComponent(lbl_editscreen)
                        .addGap(0, 0, Short.MAX_VALUE)))
            );

            getContentPane().add(edit_screeningpnl);
            edit_screeningpnl.setBounds(1020, 70, 160, 30);

            pnl_avmovie.setBackground(new java.awt.Color(46, 74, 81));
            pnl_avmovie.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

            lbl_avmovie.setFont(new java.awt.Font("Franklin Gothic Book", 1, 20)); // NOI18N
            lbl_avmovie.setForeground(new java.awt.Color(255, 255, 255));
            lbl_avmovie.setText("Available movies ");
            lbl_avmovie.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    lbl_avmovieMouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    lbl_avmovieMouseExited(evt);
                }
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    lbl_avmovieMousePressed(evt);
                }
            });

            javax.swing.GroupLayout pnl_avmovieLayout = new javax.swing.GroupLayout(pnl_avmovie);
            pnl_avmovie.setLayout(pnl_avmovieLayout);
            pnl_avmovieLayout.setHorizontalGroup(
                pnl_avmovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_avmovieLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_avmovie)
                    .addContainerGap())
            );
            pnl_avmovieLayout.setVerticalGroup(
                pnl_avmovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_avmovieLayout.createSequentialGroup()
                    .addComponent(lbl_avmovie)
                    .addGap(0, 0, Short.MAX_VALUE))
            );

            getContentPane().add(pnl_avmovie);
            pnl_avmovie.setBounds(752, 70, 180, 28);

            menu.setBackground(new java.awt.Color(46, 74, 81));
            menu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
            menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            menu_lbl.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 16)); // NOI18N
            menu_lbl.setForeground(new java.awt.Color(255, 255, 255));
            menu_lbl.setText("    MORE");
            menu_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    menu_lblMouseClicked(evt);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    menu_lblMouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    menu_lblMouseExited(evt);
                }
            });
            menu.add(menu_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 80, 30));

            getContentPane().add(menu);
            menu.setBounds(1340, 20, 80, 29);

            customer_pnl.setBackground(new java.awt.Color(46, 74, 81));
            customer_pnl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
            customer_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            lbl_customer1.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
            lbl_customer1.setForeground(new java.awt.Color(255, 255, 255));
            lbl_customer1.setText("CUSTOMERS ");
            lbl_customer1.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    lbl_customer1MouseClicked(evt);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    lbl_customer1MouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    lbl_customer1MouseExited(evt);
                }
            });
            customer_pnl.add(lbl_customer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 117, 30));

            getContentPane().add(customer_pnl);
            customer_pnl.setBounds(1290, 70, 127, 30);

            bg_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ZterView/BGBG.png"))); // NOI18N
            bg_pic.setText("jLabel1");
            getContentPane().add(bg_pic);
            bg_pic.setBounds(0, 0, 1500, 805);

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       // TODO add your handling code here:
    int selectedRowIndex = jTable1.getSelectedRow();

    if (selectedRowIndex != -1) { // Check if a row is selected
        String title = (String) jTable1.getValueAt(selectedRowIndex, 0);
        title_label.setText(" ");
    }       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
    // Get the selected row index from the table
    int selectedRowIndex = jTable1.getSelectedRow();

    if (selectedRowIndex != -1) { // Check if a row is selected
        // Get the movieID and status from the selected row of the table
        String title = (String) jTable1.getValueAt(selectedRowIndex, 0);
        String newStatus = (String) jComboBox2.getSelectedItem();

        // Call the set_status method in the edit_screening_controller
        edit_screening_controller controller = new edit_screening_controller();
        controller.updateMovieStatus(newStatus, title);
        System.out.println(newStatus);
        System.out.println(title);


    } else {
        JOptionPane.showMessageDialog(null, "Select a status");
    }
    }//GEN-LAST:event_btn_updateActionPerformed

     public void setColor(JPanel p){
    p.setBackground(new Color(24, 28, 31));
}
    public void resetColor(JPanel p1){
    p1.setBackground(new Color(46,74,81));}
    
    public void menu_btncolor(JPanel p2){
    p2.setBackground(new Color(0,0,0));}
    
    public void remenu_btncolor(JPanel p2){
    p2.setBackground(new Color(46,74,81));}
    
 
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    int selectedRowIndex = jTable1.getSelectedRow();

    if (selectedRowIndex != -1) { // Check if a row is selected
        String title = (String) jTable1.getValueAt(selectedRowIndex, 0);
        title_label.setText(title);
    }
    }//GEN-LAST:event_jTable1MouseClicked

    private void lbl_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_dashboardMouseEntered
        setColor(dashboard_btn);
    }//GEN-LAST:event_lbl_dashboardMouseEntered

    private void lbl_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_dashboardMouseExited
        resetColor(dashboard_btn);
    }//GEN-LAST:event_lbl_dashboardMouseExited

    private void lbl_dashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_dashboardMousePressed
        Dashboard_1 dash2= new Dashboard_1();
        dash2.setVisible(true);
        this.hide();
    }//GEN-LAST:event_lbl_dashboardMousePressed

    private void lbl_admovie3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_admovie3MouseEntered
        setColor(pnl_admovie3);
    }//GEN-LAST:event_lbl_admovie3MouseEntered

    private void lbl_admovie3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_admovie3MouseExited
        resetColor(pnl_admovie3);
    }//GEN-LAST:event_lbl_admovie3MouseExited

    private void lbl_admovie3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_admovie3MousePressed
        zter_AddMovies added= new zter_AddMovies();
        this.hide();
        added.setVisible(true);
    }//GEN-LAST:event_lbl_admovie3MousePressed

    private void lbl_editscreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_editscreenMouseClicked
//        edit_screening es= new edit_screening();
//        this.hide();
//        es.setVisible(true);
    }//GEN-LAST:event_lbl_editscreenMouseClicked

    private void lbl_editscreenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_editscreenMouseEntered
//        setColor(edit_screeningpnl);
    }//GEN-LAST:event_lbl_editscreenMouseEntered

    private void lbl_editscreenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_editscreenMouseExited
//        resetColor(edit_screeningpnl);
    }//GEN-LAST:event_lbl_editscreenMouseExited

    private void lbl_avmovieMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_avmovieMouseEntered
        setColor(pnl_avmovie);
    }//GEN-LAST:event_lbl_avmovieMouseEntered

    private void lbl_avmovieMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_avmovieMouseExited
        resetColor(pnl_avmovie);
    }//GEN-LAST:event_lbl_avmovieMouseExited

    private void lbl_avmovieMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_avmovieMousePressed
        av_movies av1=new av_movies();
        av1.setVisible(true);
        this.hide();
    }//GEN-LAST:event_lbl_avmovieMousePressed

    private void menu_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_lblMouseClicked
        panel.setSize(80,0);
    }//GEN-LAST:event_menu_lblMouseClicked

    private void menu_lblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_lblMouseEntered
        panel.setSize(80,70);
        setColor(menu);
    }//GEN-LAST:event_menu_lblMouseEntered

    private void menu_lblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_lblMouseExited
        //       panel.setSize(0,0);
        resetColor(menu);
    }//GEN-LAST:event_menu_lblMouseExited

    private void logout_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_lblMouseClicked
        Landing101 lan1 = new Landing101();
        lan1.setVisible(true);
        this.hide();
    }//GEN-LAST:event_logout_lblMouseClicked

    private void logout_lblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_lblMouseEntered
        menu_btncolor(logout);
        panel.setSize(80,70);
        setColor(menu);
    }//GEN-LAST:event_logout_lblMouseEntered

    private void logout_lblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_lblMouseExited
        remenu_btncolor(logout);
        panel.setSize(80,0);
    }//GEN-LAST:event_logout_lblMouseExited

    private void profile_lbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profile_lbl1MouseClicked
        Profile_1 pro1 = new Profile_1();
        pro1.setVisible(true);
        this.hide();
    }//GEN-LAST:event_profile_lbl1MouseClicked

    private void profile_lbl1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profile_lbl1MouseEntered
        panel.setSize(80,70);
        menu_btncolor(profile_panel1);

        setColor(menu);
    }//GEN-LAST:event_profile_lbl1MouseEntered

    private void profile_lbl1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profile_lbl1MouseExited
        remenu_btncolor(profile_panel1);
    }//GEN-LAST:event_profile_lbl1MouseExited

    private void panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseEntered
        panel.setSize(80,70);
        setColor(menu);
    }//GEN-LAST:event_panelMouseEntered

    private void panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseExited
        panel.setSize(80,0);
        resetColor(menu);
    }//GEN-LAST:event_panelMouseExited

    private void lbl_customer1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_customer1MouseClicked
        Customer c1= new Customer();
        c1.setVisible(true);
        this.hide();
    }//GEN-LAST:event_lbl_customer1MouseClicked

    private void lbl_customer1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_customer1MouseEntered
        setColor(customer_pnl);
        panel.setSize(80,0);

    }//GEN-LAST:event_lbl_customer1MouseEntered

    private void lbl_customer1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_customer1MouseExited
        resetColor(customer_pnl);
    }//GEN-LAST:event_lbl_customer1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_screening_controller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_screening_controller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_screening_controller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_screening_controller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edit_screening().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_pic;
    private javax.swing.JButton btn_update;
    private javax.swing.JPanel customer_pnl;
    private javax.swing.JPanel dashboard_btn;
    private javax.swing.JPanel edit_screeningpnl;
    private javax.swing.JLabel entryllbl;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_admovie3;
    private javax.swing.JLabel lbl_avmovie;
    private javax.swing.JLabel lbl_customer1;
    private javax.swing.JLabel lbl_dashboard;
    private javax.swing.JLabel lbl_editscreen;
    private javax.swing.JPanel logout;
    private javax.swing.JLabel logout_lbl;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel menu_lbl;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel pnl_admovie3;
    private javax.swing.JPanel pnl_avmovie;
    private javax.swing.JLabel profile_lbl1;
    private javax.swing.JPanel profile_panel1;
    private javax.swing.JLabel title_label;
    // End of variables declaration//GEN-END:variables
}
