/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.awt.Toolkit;
import junit.framework.Assert;
import model.forgot_password_model;
/**
 *
 * @author acer
 */
public class forgot_password extends javax.swing.JFrame {

    /**
     * Creates new form forgot_password
     */
    public forgot_password() {
        initComponents();
        setTitle("Forgot Password");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/movie-projector 2.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        confirm_password_field = new javax.swing.JTextField();
        password_field = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        email_field = new javax.swing.JTextField();
        sec_1_field = new javax.swing.JTextField();
        sec_2_field = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        reset_password_button = new javax.swing.JButton();
        login_label = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        confirm_password_field.setText("CONFIRM PASSWORD");
        getContentPane().add(confirm_password_field);
        confirm_password_field.setBounds(80, 340, 310, 30);

        password_field.setText("NEW PASSWORD");
        getContentPane().add(password_field);
        password_field.setBounds(80, 300, 310, 30);

        jLabel3.setBackground(new java.awt.Color(46, 74, 81));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SET NEW PASSWORD");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 270, 170, 16);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AUTHENTICATION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(128, 45, 230, 32);

        email_field.setText("EMAIL");
        email_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_fieldActionPerformed(evt);
            }
        });
        getContentPane().add(email_field);
        email_field.setBounds(80, 120, 300, 30);

        sec_1_field.setText("WHAT CITY WERE YOU BORN IN?");
        getContentPane().add(sec_1_field);
        sec_1_field.setBounds(80, 190, 310, 30);

        sec_2_field.setText("WHAT IS YOUR FAVOURITE ICE-CREAM FLAVOUR?");
        sec_2_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sec_2_fieldActionPerformed(evt);
            }
        });
        getContentPane().add(sec_2_field);
        sec_2_field.setBounds(80, 230, 310, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ENTER THE DETAILS YOU REGISTERED WHILE SIGNING UP");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 90, 361, 16);

        reset_password_button.setBackground(new java.awt.Color(51, 51, 51));
        reset_password_button.setForeground(new java.awt.Color(255, 255, 255));
        reset_password_button.setText("RESET PASSWORD");
        reset_password_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_password_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(reset_password_button);
        reset_password_button.setBounds(170, 383, 160, 30);

        login_label.setForeground(new java.awt.Color(255, 255, 255));
        login_label.setText("REMEMBER THE PASSWORD? LOGIN");
        login_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_labelMouseClicked(evt);
            }
        });
        getContentPane().add(login_label);
        login_label.setBounds(130, 430, 270, 16);

        jToggleButton1.setBackground(new java.awt.Color(102, 102, 102));
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("check email");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(190, 160, 111, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LOGINBG.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 500, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void email_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_fieldActionPerformed

    private void sec_2_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sec_2_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sec_2_fieldActionPerformed

    private void reset_password_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_password_buttonActionPerformed
        // TODO add your handling code here:
        String email=email_field.getText();
        String sec_1=sec_1_field.getText();
        String sec_2=sec_2_field.getText();
        String password=password_field.getText();
        String confirm_password=confirm_password_field.getText();
//        Assert.assertEquals(false, email_field.getText().length()==0); // Assert that username is not  empty
//        Assert.assertEquals(false, password_field.getText().length()==0); // Assert that password is not  empty
//        Assert.assertEquals(false, confirm_password_field.getText().length()==0); // Assert that confirm password is not  empty
//        Assert.assertEquals(false, sec_1_field.getText().length()==0); // Assert that security 1 is not  empty
//        Assert.assertEquals(false, sec_2_field.getText().length()==0); // Assert that security 2 is not  empty
        forgot_password_model fp1=new forgot_password_model();
        fp1.authentication_user(email,sec_1,sec_2,password,confirm_password);
        
    }//GEN-LAST:event_reset_password_buttonActionPerformed

    private void login_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_labelMouseClicked
        // TODO add your handling code here:
        login l1=new login();
        l1.show();
        dispose();
    }//GEN-LAST:event_login_labelMouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        String email=email_field.getText();
        forgot_password_model fp1=new forgot_password_model();
        fp1.authentication_email(email);
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgot_password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField confirm_password_field;
    private javax.swing.JTextField email_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel login_label;
    private javax.swing.JTextField password_field;
    private javax.swing.JButton reset_password_button;
    private javax.swing.JTextField sec_1_field;
    private javax.swing.JTextField sec_2_field;
    // End of variables declaration//GEN-END:variables
}
