/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//setPreferredSize(new java.awt.Dimension(1020, 329));
package view;
import com.itextpdf.text.Document;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.FileOutputStream;
import java.io.IOException;

import javax.swing.JFrame;

import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.pdf.PdfWriter;

import model.reciept_model;

/**
 *
 * @author acer
 */
public class normal_ticket extends javax.swing.JFrame {
    private reciept_model rm1;
    /**
     * Creates new form normal_ticket
     */
    public normal_ticket(reciept_model rm1) {
        initComponents();
        this.rm1 = rm1;
        updateLabels();
    }
    private void updateLabels() {
        if (rm1 != null) {
            String title = rm1.getTitle();
            String date = rm1.getShowing_date();
            String showtime=rm1.getShowtime();
            title_label.setText(title);
            showing_date_label.setText(date);
            show_time_label.setText(showtime);

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generatePDFButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        title_label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        showing_date_label = new javax.swing.JLabel();
        show_time_label = new javax.swing.JLabel();
        class_label = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        generatePDFButton.setText("DOWNLOAD TICKET");
        generatePDFButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatePDFButtonActionPerformed(evt);
            }
        });
        getContentPane().add(generatePDFButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 200, -1));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, -1, -1));

        title_label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        title_label.setText("TITLE");
        getContentPane().add(title_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 160, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("4th Floor NLIC City Center Mall, 33, Kamalpokhari");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 653, -1));

        showing_date_label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        showing_date_label.setText("SHOWING_DATE");
        getContentPane().add(showing_date_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 101, -1));

        show_time_label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        show_time_label.setText("TIME");
        getContentPane().add(show_time_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 150, -1));

        class_label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        class_label.setText("NORMAL");
        getContentPane().add(class_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 61, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText(" MORE INFO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, -1, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("SCAN HERE");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 40, 100, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("MOVIE");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 67, 82, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("SHOWDATE");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 119, 100, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("TIME");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 177, 43, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("CLASS");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 43, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/normal_ticket_1.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generatePDFButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatePDFButtonActionPerformed
        // TODO add your handling code here:
        generatePDF(); 
       
    }//GEN-LAST:event_generatePDFButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        av_movies av1=new av_movies();
        av1.show();
        dispose();

    }//GEN-LAST:event_jButton1ActionPerformed
private BufferedImage captureScreenshot(JFrame frame) {
    BufferedImage screenshot = new BufferedImage(frame.getWidth(), frame.getHeight(), BufferedImage.TYPE_INT_RGB);
    Graphics2D graphics = screenshot.createGraphics();
    frame.paint(graphics);
    graphics.dispose();
    return screenshot;
}
private void generatePDF() {
    Document document = new Document();
    try {
        generatePDFButton.setVisible(false);
        PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream("ticket.pdf"));
        document.open();
        
        // Capture the screenshot of the JFrame form
        BufferedImage screenshot = captureScreenshot(this); // Replace 'frame' with the reference to your JFrame instance

        // Create an Image instance from the screenshot
        Image image = Image.getInstance(writer, screenshot, 1.0f);
        image.scaleToFit(PageSize.A4.getWidth(), PageSize.A4.getHeight());

        // Add the image to the PDF document
        document.add(image);

        document.close();
        System.out.println("PDF generated successfully!");
        generatePDFButton.setVisible(true);
    } catch (DocumentException | IOException e) {
        e.printStackTrace();
    }
}

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(normal_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(normal_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(normal_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(normal_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new normal_ticket(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel class_label;
    private javax.swing.JButton generatePDFButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel show_time_label;
    private javax.swing.JLabel showing_date_label;
    private javax.swing.JLabel title_label;
    // End of variables declaration//GEN-END:variables
}
