package view;

/**
 *
 * @author haseena
 */
import org.jfree.data.category.DefaultCategoryDataset;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.general.DefaultPieDataset;
import controller.profile_controller;
public class Profile_1 extends javax.swing.JFrame {

    /**
     * Creates new form Profile
     */
    public Profile_1() {
        initComponents();
        setTitle("Admin Profile");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/movie-projector 2.png")));
        updatemovietitleLabel();
        updateTotalPaymentLabel();
        updateMoviesLabel();
        showBarGraph();
        showLineGraph();
        showPieChart();
        
    }
    
    
    public DefaultPieDataset getMovieTitleDataset() {
    profile_controller pc1 =new profile_controller();
    DefaultPieDataset dataset=pc1.getMovieTitleDataset();
    return dataset;
}
 public void showBarGraph() {
    profile_controller dbController = new profile_controller();
    DefaultCategoryDataset dataset = dbController.getMovieQuantityDataset();

    JFreeChart barChart = ChartFactory.createBarChart(
            "Total Payment in a Day",
            "Movie",
            "Quantity",
            dataset
    );

    CategoryPlot plot = (CategoryPlot) barChart.getPlot();
    ((BarRenderer) plot.getRenderer()).setMaximumBarWidth(0.05);
    plot.setBackgroundPaint(Color.BLACK);

    ChartPanel chartPanel = new ChartPanel(barChart);
    bargraph.setIcon(new ImageIcon(chartPanel.getChart().createBufferedImage(660, 400)));
}

  
  public void showPieChart() {
    DefaultPieDataset dataset = getMovieTitleDataset();

    // Create the pie chart
    JFreeChart pieChart = ChartFactory.createPieChart(
            "Movie Titles", // Chart title
            dataset, // Dataset
            true, // Include legend
            true, // Include tooltips
            false // Include URLs
    );

    // Create a ChartPanel to display the chart
    ChartPanel chartPanel = new ChartPanel(pieChart);

    // Set the ChartPanel to the label on your form
    pieChartLabel.setIcon(new ImageIcon(chartPanel.getChart().createBufferedImage(400, 400)));
}

    
 public void showLineGraph() {
     profile_controller pc1 =new profile_controller();
   try {
            ResultSet resultSet = pc1.fetchData();

            DefaultCategoryDataset dataset = new DefaultCategoryDataset();

            while (resultSet.next()) {
                String movieId = resultSet.getString("movieId");
                double totalPayment = resultSet.getDouble("total_payment");
                dataset.addValue(totalPayment, "Total Payment", movieId);
            }

            resultSet.close();

            JFreeChart lineChart = ChartFactory.createLineChart(
                    "Total Payment in a Day",
                    "Date",
                    "Total Payment",
                    dataset
            );

            // Rest of your code for chart configuration...

            ChartPanel chartPanel = new ChartPanel(lineChart);
            BufferedImage chartImage = chartPanel.getChart().createBufferedImage(600, 400);
            ImageIcon chartIcon = new ImageIcon(chartImage);
            linecharts.setIcon(chartIcon);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    
}
  public int getTotalPaymentSum() 
    {
        profile_controller pc1= new profile_controller();
        int sum= pc1.getTotalPaymentSum();
        return sum;
    }

    public void updateTotalPaymentLabel() {
    int totalSum = getTotalPaymentSum();
    lbltotalincome.setText(String.valueOf(totalSum));
    }

    
    public int getRowCount() {

    profile_controller pc1 =new profile_controller();
    int rowcount =pc1.getRowCount("purchased_tickets");

    return rowcount;
}

    public void updatemovietitleLabel() {
    double row_count = getRowCount();
    ticketslbl.setText(String.valueOf(row_count));
}
 public int getMoviesRowCount() {
    profile_controller pc1= new profile_controller();
    int rowCount=pc1.getRowCount("movies");

    return rowCount;
}

public void updateMoviesLabel() {
    int moviesCount = getMoviesRowCount();
    available.setText(String.valueOf(moviesCount));
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ticketslbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        available = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        bargraph = new javax.swing.JLabel();
        pieChartLabel = new javax.swing.JLabel();
        linecharts = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbltotalincome = new javax.swing.JLabel();
        bg_png = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Back.setText("Back");
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADMIN RECORDS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        ticketslbl.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 37)); // NOI18N
        ticketslbl.setForeground(new java.awt.Color(255, 255, 255));
        ticketslbl.setText("200");
        jPanel1.add(ticketslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 620, 90, 50));

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 27)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TICKETS SOLD");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 690, -1, -1));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 27)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("AVAILABLE MOVIES");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, -1, -1));

        available.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 37)); // NOI18N
        available.setForeground(new java.awt.Color(255, 255, 255));
        available.setText("200");
        jPanel1.add(available, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 80, 50));

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bargraph.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jPanel2.add(bargraph, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 890, 600, 430));
        jPanel2.add(pieChartLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 450, 400));
        jPanel2.add(linecharts, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 670, 420));

        jScrollPane1.setViewportView(jPanel2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 1010, 650));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 27)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TOTAL INCOME");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        lbltotalincome.setBackground(new java.awt.Color(255, 255, 255));
        lbltotalincome.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 37)); // NOI18N
        lbltotalincome.setForeground(new java.awt.Color(255, 255, 255));
        lbltotalincome.setText("Total");
        lbltotalincome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbltotalincomeMouseClicked(evt);
            }
        });
        jPanel1.add(lbltotalincome, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 220, 60));

        bg_png.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profilefinal.png"))); // NOI18N
        bg_png.setText("jLabel4");
        jPanel1.add(bg_png, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1505, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
//        Dashboard db = new Dashboard();
//        db.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void lbltotalincomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltotalincomeMouseClicked

    }//GEN-LAST:event_lbltotalincomeMouseClicked

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        Dashboard_1 dash5= new Dashboard_1();
        dash5.setVisible(true);
        this.hide();
        
        
    }//GEN-LAST:event_BackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel available;
    private javax.swing.JLabel bargraph;
    private javax.swing.JLabel bg_png;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbltotalincome;
    private javax.swing.JLabel linecharts;
    private javax.swing.JLabel pieChartLabel;
    private javax.swing.JLabel ticketslbl;
    // End of variables declaration//GEN-END:variables
}
