package view;

import com.itextpdf.text.Document;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Random;
import javax.swing.JFrame;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.pdf.PdfWriter;
import controller.reciept_controller;
import view.av_movies;

import model.reciept_model;

public class reciept extends javax.swing.JFrame {
    private reciept_model rm1;

    public reciept() {
        initComponents();

    }

    public void setRecieptModel(reciept_model rm1) {
        this.rm1 = rm1;
        updateLabels();
    }

    private void updateLabels() {
        if (rm1 != null) {
            String title = rm1.getTitle();
            String date = rm1.getShowing_date();
            int rate_np = rm1.getRate_np();
            String rate_np_st = Integer.toString(rate_np);
            int rate_sp = rm1.getRate_sp();
            String rate_sp_st = Integer.toString(rate_sp);
            int quantity_np = rm1.getQuantity_np();
            String quantity_np_st = Integer.toString(quantity_np);
            int quantity_sp = rm1.getQuantity_sp();
            String quantity_sp_st = Integer.toString(quantity_sp);
            Random random = new Random();
            int min = 100000; // minimum value (inclusive)
            int max = 999999; // maximum value (inclusive)
            int randomNumber = random.nextInt(max - min + 1) + min;
            String randomNumber_st = Integer.toString(randomNumber);
            title_label.setText(title);
            random_number_label.setText(randomNumber_st);
            showing_date.setText(date);
            sp_num.setText(quantity_sp_st);
            np_num.setText(quantity_np_st);
            price_sp.setText(rate_sp_st);
            price_np.setText(rate_np_st);
            int total = (rate_np * quantity_np) + (rate_sp * quantity_sp);
            String total_st = Integer.toString(total);
            total_label.setText(total_st);
            reciept_controller rc1=new reciept_controller();
            rc1.insertData(title,quantity_np, quantity_sp, rate_np, rate_sp, total,randomNumber );
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        title_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        showing_date = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sp_num = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        np_num = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        random_number_label = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        price_sp = new javax.swing.JLabel();
        price_np = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        generatePDFButton = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        total_label = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        title_label.setForeground(new java.awt.Color(255, 255, 255));
        title_label.setText("TITLE");
        getContentPane().add(title_label);
        title_label.setBounds(160, 210, 115, 16);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MOVIE:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 210, 55, 16);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DATE:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 250, 55, 16);

        showing_date.setForeground(new java.awt.Color(255, 255, 255));
        showing_date.setText("showing_date");
        getContentPane().add(showing_date);
        showing_date.setBounds(150, 250, 100, 16);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SPECIAL CLASS:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 310, 120, 16);

        sp_num.setForeground(new java.awt.Color(255, 255, 255));
        sp_num.setText("sp_num");
        getContentPane().add(sp_num);
        sp_num.setBounds(160, 280, 64, 16);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("NORMAL CLASS:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 280, 120, 16);

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 410, 72, 23);

        np_num.setForeground(new java.awt.Color(255, 255, 255));
        np_num.setText("np_num");
        getContentPane().add(np_num);
        np_num.setBounds(160, 310, 51, 16);

        jPanel2.setBackground(new java.awt.Color(0, 102, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 80));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("MOVIE RECIEPT");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/movie-projector 2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 592, 77);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("RECIEPT NUMBER:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(40, 160, 130, 16);

        random_number_label.setForeground(new java.awt.Color(255, 255, 255));
        random_number_label.setText("ranodm_number");
        getContentPane().add(random_number_label);
        random_number_label.setBounds(190, 160, 100, 16);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("PRICE:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(250, 280, 60, 16);

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("PRICE:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(250, 310, 50, 16);

        price_sp.setForeground(new java.awt.Color(255, 255, 255));
        price_sp.setText("price_sp");
        getContentPane().add(price_sp);
        price_sp.setBounds(350, 280, 60, 16);

        price_np.setForeground(new java.awt.Color(255, 255, 255));
        price_np.setText("price_np");
        getContentPane().add(price_np);
        price_np.setBounds(360, 310, 70, 16);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 340, 490, 20);

        generatePDFButton.setBackground(new java.awt.Color(102, 102, 102));
        generatePDFButton.setForeground(new java.awt.Color(255, 255, 255));
        generatePDFButton.setText("download pdf");
        generatePDFButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatePDFButtonActionPerformed(evt);
            }
        });
        getContentPane().add(generatePDFButton);
        generatePDFButton.setBounds(325, 410, 120, 23);

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("TOTAL PRICE:");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(210, 370, 100, 30);

        total_label.setForeground(new java.awt.Color(255, 255, 255));
        total_label.setText("TOTAL");
        getContentPane().add(total_label);
        total_label.setBounds(330, 370, 60, 30);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LOGINBG.png"))); // NOI18N
        getContentPane().add(jLabel20);
        jLabel20.setBounds(0, 70, 500, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generatePDFButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatePDFButtonActionPerformed
        // TODO add your handling code here:
        generatePDFButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                generatePDF();
            }
            
        });

    }//GEN-LAST:event_generatePDFButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        av_movies av1=new av_movies();
        av1.show();
        dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed
private BufferedImage captureScreenshot(JFrame frame) {
    BufferedImage screenshot = new BufferedImage(frame.getWidth(), frame.getHeight(), BufferedImage.TYPE_INT_RGB);
    Graphics2D graphics = screenshot.createGraphics();
    frame.paint(graphics);
    graphics.dispose();
    return screenshot;
}
private void generatePDF() {
    Document document = new Document();
    try {
        generatePDFButton.setVisible(false);
        PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream("output.pdf"));
        document.open();
        
        // Capture the screenshot of the JFrame form
        BufferedImage screenshot = captureScreenshot(this); // Replace 'frame' with the reference to your JFrame instance

        // Create an Image instance from the screenshot
        Image image = Image.getInstance(writer, screenshot, 1.0f);
        image.scaleToFit(PageSize.A4.getWidth(), PageSize.A4.getHeight());

        // Add the image to the PDF document
        document.add(image);

        document.close();
        System.out.println("PDF generated successfully!");
        generatePDFButton.setVisible(true);
    } catch (DocumentException | IOException e) {
        e.printStackTrace();
    }
}

    /**
     * @param args the command line arguments
     */
    // Main method to launch the application
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reciept().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generatePDFButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel np_num;
    private javax.swing.JLabel price_np;
    private javax.swing.JLabel price_sp;
    private javax.swing.JLabel random_number_label;
    private javax.swing.JLabel showing_date;
    private javax.swing.JLabel sp_num;
    private javax.swing.JLabel title_label;
    private javax.swing.JLabel total_label;
    // End of variables declaration//GEN-END:variables
}
